In [1]:
import numpy as np

In [2]:
a=np.arange(24).reshape(4,6)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
np.split(a,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [8]:
np.split(a,4,axis=0)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]])]

In [6]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
b=np.arange(100,124).reshape(4,6)

In [16]:
b

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [18]:
np.concatenate((a,b),axis=0)

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [12]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
b

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123])

In [19]:
a=np.arange(5)

In [20]:
a

array([0, 1, 2, 3, 4])

In [21]:
np.tile(a,3)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [51]:
a

array([0, 1, 2, 3, 4, 5])

In [53]:
np.repeat(a,3,axis=0)


array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [25]:
a

array([0, 1, 2, 3, 4])

In [32]:
a=np.arange(6).reshape(3,2)

In [33]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
np.repeat(a,2,axis=0)

array([[0, 1],
       [0, 1],
       [2, 3],
       [2, 3],
       [4, 5],
       [4, 5]])

In [38]:
a=np.arange(6)

In [39]:
a

array([0, 1, 2, 3, 4, 5])

In [40]:
b=np.arange(6).reshape(2,3)

In [41]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
a

array([0, 1, 2, 3, 4, 5])

In [47]:
np.repeat(b,2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])